### PR TITLE
Update documentation 🛠️

### PR DESCRIPTION
**Pull request by Azodox**
Hey, small update of the README used as a documentation concerning the events part.
Make a review @RealAlphaUA and tell me about my mistakes.

### CODE REVIEW

**Comment by RealAlphaUA** [comment]
Can you delete this part, atm that deprecated 
image

**Comment by Azodox** [comment]
There you go!

**Comment by RealAlphaUA** [comment]
Think about changing the target, replace master by dev

**Comment by RealAlphaUA** [comment]
Thanks you 🎊

**Pull request merged**
